### ISSUE TITLE
Can't compile moveit_ompl  -  error: bounds_ was not declared in this scope

### ISSUE THREAD

**Issue by DavidB-CMU** [davetcoleman/moveit_ompl#1]
Hi,
I was trying to compile your `moveit_visual_tools` in a catkin tools workspace. 
I think `moveit_ompl` is missing an include?

```
moveit_ompl/src/model_based_state_space.cpp:78:3: 
error: bounds_ was not declared in this scope bounds_.resize(joint_bounds_storage_.size());
```

Thanks

**Comment by davetcoleman** [comment]
I'm confused why you are using moveit_ompl with moveit_visual_tools - it is not a dependency. 

This repo is mostly just my own research and isn't cleaned up enough for external usage yet. It requires a custom version of OMPL in my fork

**Comment by DavidB-CMU** [comment]
Oops, I meant I'm trying to use `ompl_visual_tools`. 
The default branch is Kinetic which depends on `moveit_ompl`. 
So I guess I was using the wrong branch of  `ompl_visual_tools`.
My mistake, thanks!
