### ISSUE TITLE
How do I set MoveIt! to use the source installation of ompl for ros indigo

### ISSUE THREAD

**Issue by gxxzs** [davetcoleman/moveit_ompl#3]
I install  moveit from source for ros indigo according to the steps  did in https://github.com/ros-planning/moveit_ros/issues/623,  How do I set MoveIt! to use the source installation of ompl for ros indigo? After i remove ros-indigo-ompl and install ompl from source, moveit cannot load ompl unless   I do "sudo apt-get install ros-indigo-ompl" or “”sudo apt-get install ros-`rosversion -d`-ompl”.
My installayion process:
1. Installed MoveIt from source and "sudo apt-get remove ros-indigo-ompl" to remove ompl after moveit installed successfully.
2.MoveIt path in my ubuntu was:~/ws_moveit
Installation Link:http://moveit.ros.org/install/
3. Installation link:http://picknik.io/moveit_wiki/index.php?title=OMPL/Add_New_Planner
                            http://moveit.ros.org/install/source/dependencies/
git clone https://github.com/ompl/ompl.git
path: /home/name/ompl
cd ompl/
mkdir -p build/Release
cd build/
cmake -DCMAKE_INSTALL_PREFIX=/opt/ros/indigo ..
make install
sudo make install
cd Release/
cmake -DCMAKE_INSTALL_PREFIX=/opt/ros/indigo ..
cd ..
make -j 4 update_bindings(failed and skip this step)
make
sudo make install

Now moveit cannot load ompl, i konw something should be do to link ompl to moveit, but I donot know how, can anyone give me some advice, thanks.

**Comment by yt100323** [comment]
I am doing the same thing and I found other ways, it seems work but the planning will go crash, here is the link https://github.com/davetcoleman/moveit_ompl/issues/2, I cannot solve the preoblem, can we have a check?
